
# SIMULACION
REPLICAS = 1
DIAS_SIMULACION = 365
HORA_INICIAL = 7
HORA_TERMINO = 17
PROBABILIDAD_LLUVIA = 0.3
PROBABILIDAD_LLUVIA_INCREMENTO = 0 #0.0002
X_MAX_MAPA = 10
Y_MAX_MAPA = 10

# CAMIONES
CAMIONES_MIN = 3
CAMIONES_MAX = 15
CAPACIDAD_CAMION = 30  # toneladas
VELOCIDAD_CAMION = 40  # km/h

# COSTOS
COSTO_TRANSPORTE = 0.1  # $/tonelada/km
COSTO_INVENTARIO = 0.35  # $/tonelada/dia (a)
COSTO_QUIEBRE_STOCK = 1050.33  # $ (b)

# PLANTAS
PLANTAS = [(3, 2, "Normal", (4000, 200)),
           (7, 5, "Normal", (5000, 300)),
           (4, 8, "Triangualar", (4000, 5500, 7000))]

# CELDAS
CELDA_PRODUCCION = 100000  # toneladas

# POLITICAS DE REPOSICION
POLITICA_REPOSICION = "D"  # "E: E" o "D: Dinamica"

# POLITICA DE REPOSICION ESTATICA
INVENTARIO_OBJETIVO = 3 # veces la demanda promedio diaria
INVENTARIO_ALARMA = 3 # veces la demanda promedio diaria

# FACTORES POLITICA DE REPOSICION DINAMICA
IMPORTANCIA_DEMANDA = 1
IMPORTANCIA_INVENTARIO = 1
IMPORTANCIA_DISTANCIA = 1
